/**
 * Catalogue élargi PC Star.
 *
 * Ces références structurent les nouveaux rayons demandés pour la vitrine :
 * impression/POS, ordinateurs de marque et reconditionnés, réseau/énergie,
 * mobilité, multimédia et mobilier. Les prix et le stock restent des données de
 * démonstration du catalogue : le comptoir doit les confirmer avant mise en
 * production et peut ensuite les remplacer depuis l'administration.
 *
 * `photoMode: 'mark'` évite d'afficher une photo générique trompeuse sur une
 * référence qui n'a pas encore reçu sa vraie photo : la vignette montre le
 * repère lisible de sa famille jusqu'à l'ajout des photos du magasin.
 */
const PHOTO_GROUP_BY_CATEGORY = {
  printer: 'printer-studio',
  scanner: 'printer-studio',
  consumables: 'printer-studio',
  pos: 'pos-studio',
  desktop: 'desktop-studio',
  allinone: 'desktop-studio',
  server: 'desktop-studio',
  laptop: 'laptop-studio',
  network: 'network-studio',
  power: 'network-studio',
  laptop_accessories: 'laptop-accessories-studio',
  multimedia: 'multimedia-studio',
  furniture: 'furniture-studio',
  tablet: 'mobile-studio',
  phone: 'mobile-studio',
  monitor: 'monitor-studio',
  cpu: 'components-studio',
  gpu: 'components-studio',
  motherboard: 'components-studio',
  memory: 'components-studio',
  case: 'components-studio',
  cooling: 'components-studio',
  accessories: 'components-studio'
}

function p(id, sku, name, brand, kind, category, price, stock, short, extra = {}) {
  const photoGroup = extra.photoGroup || PHOTO_GROUP_BY_CATEGORY[category]
  // P27 — quand une photo a été livrée pour CETTE référence (`extra.packshot`,
  // générée pour le rayon puis rangée dans /photos/pack/), elle prend la place de
  // l'illustration de famille : le badge « illustration de catégorie » disparaît,
  // et la fiche montre un visuel qui parle d'elle, pas de son rayon.
  const photos = extra.packshot ? [extra.packshot] : photoGroup ? [`/catalog/${photoGroup}.jpg`] : []
  return {
    id,
    sku,
    name,
    brand,
    kind,
    category,
    price,
    stock,
    rating: extra.rating ?? 4.3,
    reviews: extra.reviews ?? 12,
    related: [],
    // Visuels de rayon générés spécialement pour PC Star. Il s'agit d'une
    // illustration de famille (pas de la promesse d'une photo exacte du SKU),
    // remplaçable par les vraies photos reçues au comptoir.
    photos,
    photoMode: extra.packshot ? 'packshot' : photoGroup ? 'category' : 'mark',
    short,
    condition: extra.condition || 'new',
    uses: extra.uses || [],
    warrantyMonths: extra.warrantyMonths ?? (extra.condition === 'used' ? 3 : extra.condition === 'refurbished' ? 6 : 12),
    tags: extra.tags || [],
    needsKey: 'needsExpanded',
    compat: extra.compat || {},
    origin: 'expanded'
  }
}

export const CATALOG_EXTENSIONS = [
  // ——— Imprimantes, scanners, caisse & consommables ———
  p('prn-hp-107a', 'HP-107A', 'HP Laser 107a monochrome', 'HP', 'accessory', 'printer', 24500, 5,
    'Laser A4 · USB · 20 ppm', { packshot: '/photos/pack/prn-hp-107a.jpg', photoGroup: 'printer-laser-studio', uses: ['office', 'student'] }),
  p('prn-brother-1610w', 'BRO-DCP-1610W', 'Brother DCP-1610W multifonction laser Wi‑Fi', 'Brother', 'accessory', 'printer', 36500, 3,
    'Impression · scan · copie · Wi‑Fi', { packshot: '/photos/pack/prn-brother-1610w.jpg', photoGroup: 'printer-laser-studio', uses: ['office', 'student'] }),
  p('prn-epson-l3250', 'EPS-L3250', 'Epson EcoTank L3250 multifonction', 'Epson', 'accessory', 'printer', 44500, 4,
    'Réservoir d’encre · Wi‑Fi · couleur', { packshot: '/photos/pack/prn-epson-l3250.jpg', photoGroup: 'printer-ink-studio', uses: ['office', 'student'] }),
  p('prn-hp-515', 'HP-SMART-515', 'HP Smart Tank 515 multifonction', 'HP', 'accessory', 'printer', 41500, 3,
    'Réservoir d’encre · couleur', { packshot: '/photos/pack/prn-hp-515.jpg', photoGroup: 'printer-ink-studio', uses: ['office', 'student'] }),
  p('prn-xprinter-q200', 'XP-Q200', 'XPrinter Q200 imprimante ticket thermique', 'XPrinter', 'accessory', 'printer', 11800, 7,
    '80 mm · USB / Ethernet', { packshot: '/photos/pack/prn-xprinter-q200.jpg', photoGroup: 'printer-ticket-studio', uses: ['retail'], tags: ['thermal', 'pos'] }),
  p('prn-xprinter-420b', 'XP-420B', 'XPrinter XP-420B imprimante étiquettes', 'XPrinter', 'accessory', 'printer', 18500, 4,
    'Code-barres · étiquettes 4 pouces', { packshot: '/photos/pack/prn-xprinter-420b.jpg', photoGroup: 'printer-ticket-studio', uses: ['retail'], tags: ['label', 'pos'] }),
  p('prn-epson-lx350', 'EPS-LX350', 'Epson LX-350 imprimante matricielle', 'Epson', 'accessory', 'printer', 39800, 2,
    '9 aiguilles · formulaires', { packshot: '/photos/pack/prn-epson-lx350.jpg', uses: ['office', 'retail'], tags: ['matrix'] }),
  p('scn-canon-lide300', 'CAN-LIDE300', 'Canon CanoScan LiDE 300', 'Canon', 'accessory', 'scanner', 19500, 4,
    'Scanner A4 à plat · USB', { packshot: '/photos/pack/scn-canon-lide300.jpg', photoGroup: 'scanner-studio', uses: ['office', 'student'] }),
  p('scn-hp-pro2600', 'HP-SJ-PRO2600', 'HP ScanJet Pro 2600 f1', 'HP', 'accessory', 'scanner', 54800, 2,
    'Scanner recto verso · chargeur documents', { packshot: '/photos/pack/scn-hp-pro2600.jpg', photoGroup: 'scanner-studio', uses: ['office', 'business'] }),
  p('pos-honeywell-1250g', 'HON-1250G', 'Honeywell Voyager 1250g lecteur code-barres', 'Honeywell', 'accessory', 'pos', 9800, 6,
    'Laser 1D · USB', { packshot: '/photos/pack/pos-honeywell-1250g.jpg', photoGroup: 'barcode-studio', uses: ['retail'], tags: ['barcode'] }),
  p('pos-drawer-410', 'POS-CD410', 'Tiroir-caisse 410 mm RJ11', 'Generic', 'accessory', 'pos', 8500, 5,
    'Métal · 5 billets / 8 monnaies', { packshot: '/photos/pack/pos-drawer-410.jpg', uses: ['retail'] }),
  p('pos-sunmi-v2s', 'SUNMI-V2S', 'Terminal POS Sunmi V2S Android', 'Sunmi', 'accessory', 'pos', 42000, 2,
    'Terminal mobile · imprimante ticket intégrée', { packshot: '/photos/pack/pos-sunmi-v2s.jpg', uses: ['retail'] }),
  p('con-hp-107a', 'TONER-107A', 'Toner compatible HP 107A', 'Ink Master', 'accessory', 'consumables', 2800, 16,
    'Noir · HP Laser 107 / MFP 135', { packshot: '/photos/pack/con-hp-107a.jpg', photoGroup: 'toner-ink-studio', uses: ['office'], tags: ['toner'] }),
  p('con-bro-tn1000', 'TONER-TN1000', 'Toner compatible Brother TN-1000', 'Ink Master', 'accessory', 'consumables', 2900, 14,
    'Noir · Brother DCP-1610W', { packshot: '/photos/pack/con-bro-tn1000.jpg', photoGroup: 'toner-ink-studio', uses: ['office'], tags: ['toner'] }),
  p('con-epson-003bk', 'EPS-003-BK', 'Encre Epson 003 noire', 'Epson', 'accessory', 'consumables', 1450, 20,
    'Bouteille noire · EcoTank', { packshot: '/photos/pack/con-epson-003bk.jpg', photoGroup: 'toner-ink-studio', uses: ['office', 'student'], tags: ['ink'] }),
  p('con-epson-003cmy', 'EPS-003-CMY', 'Pack encres Epson 003 couleurs', 'Epson', 'accessory', 'consumables', 3900, 12,
    'Cyan · magenta · jaune', { packshot: '/photos/pack/con-epson-003cmy.jpg', photoGroup: 'toner-ink-studio', uses: ['office', 'student'], tags: ['ink'] }),
  p('con-a4-80', 'PAPER-A4-80', 'Papier A4 80 g · ramette 500 feuilles', 'Double A', 'accessory', 'consumables', 950, 30,
    'Blanc · impression bureautique', { packshot: '/photos/pack/con-a4-80.jpg', photoGroup: 'paper-label-studio', uses: ['office', 'student'], tags: ['paper'] }),
  p('con-ticket-8080', 'TICKET-80-80', 'Rouleau ticket caisse 80 × 80 mm', 'Generic', 'accessory', 'consumables', 280, 50,
    'Papier thermique', { packshot: '/photos/pack/con-ticket-8080.jpg', photoGroup: 'paper-label-studio', uses: ['retail'], tags: ['paper', 'thermal'] }),
  p('con-label-100150', 'LABEL-100-150', 'Étiquettes thermiques 100 × 150 mm', 'Generic', 'accessory', 'consumables', 1650, 18,
    'Rouleau expédition / code-barres', { packshot: '/photos/pack/con-label-100150.jpg', photoGroup: 'paper-label-studio', uses: ['retail'], tags: ['label'] }),

  // ——— Ordinateurs de marque, bureau, serveur et occasion ———
  p('desk-dell-7060', 'OPT-7060-I5-8-256', 'Dell OptiPlex 7060 i5 / 8 Go / SSD 256 Go', 'Dell', 'machine', 'desktop', 47900, 4,
    'PC de marque · Windows · SFF', { packshot: '/photos/pack/desk-dell-7060.jpg', condition: 'refurbished', uses: ['office', 'business'] }),
  p('desk-hp-600g5', 'HP-600G5-I5-8-256', 'HP ProDesk 600 G5 i5 / 8 Go / SSD 256 Go', 'HP', 'machine', 'desktop', 49500, 4,
    'PC bureau reconditionné', { packshot: '/photos/pack/desk-hp-600g5.jpg', condition: 'refurbished', uses: ['office', 'business'] }),
  p('desk-len-m720s', 'LEN-M720S-I5-8-256', 'Lenovo ThinkCentre M720s i5 / 8 Go / SSD 256 Go', 'Lenovo', 'machine', 'desktop', 47500, 3,
    'PC de marque · compact', { condition: 'refurbished', uses: ['office', 'business'] }),
  p('desk-dell-7070m', 'OPT-7070M-I5-8-256', 'Dell OptiPlex 7070 Micro i5 / 8 Go / SSD 256 Go', 'Dell', 'machine', 'desktop', 53500, 3,
    'Mini PC reconditionné · Wi‑Fi', {photoGroup: 'mini-pc-studio',  condition: 'refurbished', uses: ['office', 'business'], tags: ['mini'] }),
  p('desk-hp-elitedesk', 'HP-800G5-I7-16-512', 'HP EliteDesk 800 G5 i7 / 16 Go / SSD 512 Go', 'HP', 'machine', 'desktop', 68500, 2,
    'PC professionnel reconditionné', { condition: 'refurbished', uses: ['business', 'creative'] }),
  p('aio-hp-24', 'HP-AIO-24-I5', 'HP All-in-One 24 pouces i5 / 8 Go / SSD 512 Go', 'HP', 'machine', 'allinone', 98500, 2,
    'Écran et PC intégrés · Wi‑Fi', { photoGroup: 'allinone-studio', uses: ['office', 'student'] }),
  p('aio-dell-3280', 'DELL-AIO-3280-I5', 'Dell OptiPlex 3280 All-in-One i5', 'Dell', 'machine', 'allinone', 69500, 2,
    '21,5 pouces · reconditionné', { photoGroup: 'allinone-studio', condition: 'refurbished', uses: ['office', 'business'] }),
  p('ws-hp-z2g4', 'HP-Z2G4-I7-32-1T', 'HP Z2 G4 Workstation i7 / 32 Go / SSD 1 To', 'HP', 'machine', 'desktop', 128000, 1,
    'Station de travail · CAO / montage', { photoGroup: 'server-studio', condition: 'refurbished', uses: ['creative', 'business'], tags: ['workstation'] }),
  p('srv-dell-t140', 'DELL-T140-XEON-16', 'Dell PowerEdge T140 Xeon / 16 Go', 'Dell', 'machine', 'server', 178000, 1,
    'Serveur tour · stockage entreprise', { photoGroup: 'server-studio', uses: ['business'], tags: ['server'] }),
  p('srv-hp-ml30', 'HP-ML30-XEON-16', 'HPE ProLiant ML30 Gen10 Xeon / 16 Go', 'HPE', 'machine', 'server', 195000, 1,
    'Serveur PME · évolutif', { photoGroup: 'server-studio', uses: ['business'], tags: ['server'] }),
  p('lap-len-v15', 'LEN-V15-G4-I3-8-256', 'Lenovo V15 G4 i3 / 8 Go / SSD 256 Go', 'Lenovo', 'machine', 'laptop', 63500, 4,
    '15,6 pouces · étudiant / bureau', { packshot: '/photos/pack/lap-len-v15.jpg', uses: ['student', 'office'] }),
  p('lap-asus-go15', 'ASUS-E1504-8-512', 'ASUS Vivobook Go 15 / 8 Go / SSD 512 Go', 'ASUS', 'machine', 'laptop', 68500, 4,
    '15,6 pouces FHD · Ryzen 3', { uses: ['student', 'office'] }),
  p('lap-len-loq15', 'LEN-LOQ15-I5-RTX3050', 'Lenovo LOQ 15 i5 / RTX 3050 / 16 Go', 'Lenovo', 'machine', 'laptop', 156000, 2,
    '15,6 pouces 144 Hz · gaming', { photoGroup: 'laptop-gaming-studio', uses: ['gaming', 'creative'] }),
  p('lap-hp-840g5', 'HP-840G5-I5-8-256', 'HP EliteBook 840 G5 i5 / 8 Go / SSD 256 Go', 'HP', 'machine', 'laptop', 57900, 4,
    '14 pouces · chargeur inclus', { photoGroup: 'laptop-business-studio', condition: 'refurbished', uses: ['business', 'student'] }),
  p('lap-dell-5410-used', 'DELL-5410-I5-8-256', 'Dell Latitude 5410 i5 / 8 Go / SSD 256 Go', 'Dell', 'machine', 'laptop', 69900, 3,
    '14 pouces FHD · chargeur inclus', { photoGroup: 'laptop-business-studio', condition: 'refurbished', uses: ['business', 'student'] }),
  p('lap-len-l490-used', 'LEN-L490-I5-8-256', 'Lenovo ThinkPad L490 i5 / 8 Go / SSD 256 Go', 'Lenovo', 'machine', 'laptop', 54900, 4,
    '14 pouces · occasion contrôlée', { photoGroup: 'laptop-business-studio', condition: 'used', uses: ['business', 'student'] }),
  p('lap-macair-2017', 'MBA-2017-I5-8-128', 'MacBook Air 2017 i5 / 8 Go / SSD 128 Go', 'Apple', 'machine', 'laptop', 64500, 1,
    '13 pouces · chargeur inclus', { photoGroup: 'laptop-business-studio', condition: 'used', uses: ['student', 'office'] }),
  p('gpu-1660-used', 'GTX-1660S-6G-OCC', 'NVIDIA GTX 1660 Super 6 Go', 'NVIDIA', 'part', 'gpu', 36500, 2,
    'Carte graphique occasion testée', {photoGroup: 'gpu-studio',  condition: 'used', uses: ['gaming'], warrantyMonths: 1, tags: ['used'], compat: { psuMin: 450 } }),
  p('ssd-256-used', 'SSD-256-OCC', 'SSD 256 Go SATA reconditionné', 'Kingston', 'part', 'memory', 3200, 5,
    'Santé contrôlée · 2,5 pouces', {photoGroup: 'ssd-studio',  condition: 'refurbished', uses: ['office', 'student'], warrantyMonths: 3, tags: ['used'] }),

  // ——— Configurateur : formats compacts mATX (phase 6) ———
  p('mb-asrock-b450m', 'ASR-B450M-HDV', 'ASRock B450M-HDV R4.0 · AM4', 'ASRock', 'part', 'motherboard', 11500, 5,
    'AM4 · mATX · DDR4 · M.2', { photoGroup: 'motherboard-studio', uses: ['office', 'student'], compat: { socket: 'AM4', memory: 'DDR4', form: 'mATX' } }),
  p('case-havit-matx', 'HAV-MC-RC', 'Boîtier Havit Micro ATX', 'Havit', 'part', 'case', 5400, 6,
    'mATX · USB 3.0 · 1 ventilateur', { photoGroup: 'case-studio', uses: ['office', 'student'], compat: { form: 'mATX' }, tags: ['case'] }),
  p('case-cm-q300l', 'CM-Q300L', 'Cooler Master MasterBox Q300L mATX', 'Cooler Master', 'part', 'case', 7900, 4,
    'mATX · mesh · 2 ventilateurs', { photoGroup: 'case-studio', uses: ['gaming', 'office'], compat: { form: 'mATX' }, tags: ['case'] }),

  // ——— Réseau, onduleurs et électricité ———
  p('net-tp-ax12', 'TPL-AX12', 'TP-Link Archer AX12 Wi‑Fi 6', 'TP-Link', 'accessory', 'network', 8200, 7,
    'Routeur AX1500 double bande', { packshot: '/photos/pack/net-tp-ax12.jpg', photoGroup: 'router-studio', uses: ['office', 'gaming'] }),
  p('net-tenda-f3', 'TEN-F3', 'Tenda F3 routeur Wi‑Fi N300', 'Tenda', 'accessory', 'network', 3400, 12,
    'Routeur maison · budget', { packshot: '/photos/pack/net-tenda-f3.jpg', photoGroup: 'router-studio', uses: ['office', 'student'], tags: ['budget'] }),
  p('net-tp-re305', 'TPL-RE305', 'TP-Link RE305 répéteur Wi‑Fi AC1200', 'TP-Link', 'accessory', 'network', 5200, 8,
    'Répéteur double bande', { packshot: '/photos/pack/net-tp-re305.jpg', photoGroup: 'router-studio', uses: ['office', 'student'] }),
  p('net-tp-eap115', 'TPL-EAP115', 'TP-Link EAP115 point d’accès plafond', 'TP-Link', 'accessory', 'network', 8500, 4,
    'Wi‑Fi entreprise · PoE', { packshot: '/photos/pack/net-tp-eap115.jpg', photoGroup: 'router-studio', uses: ['business'] }),
  p('net-tp-ls1008g', 'TPL-LS1008G', 'TP-Link LS1008G switch Gigabit 8 ports', 'TP-Link', 'accessory', 'network', 5900, 7,
    'Switch réseau non manageable', { packshot: '/photos/pack/net-tp-ls1008g.jpg', uses: ['office', 'business'] }),
  p('net-tp-t2u', 'TPL-ARCHER-T2U', 'TP-Link Archer T2U Nano Wi‑Fi USB', 'TP-Link', 'accessory', 'network', 2500, 14,
    'Adaptateur Wi‑Fi AC600', { packshot: '/photos/pack/net-tp-t2u.jpg', uses: ['office', 'student'] }),
  p('net-pcie-gbe', 'PCIe-GBE', 'Carte réseau PCIe Gigabit', 'TP-Link', 'accessory', 'network', 1900, 9,
    'RJ45 10/100/1000 Mbps', { packshot: '/photos/pack/net-pcie-gbe.jpg', uses: ['office', 'business'] }),
  p('net-cat6-20m', 'CAT6-20M', 'Câble réseau CAT6 20 m', 'Generic', 'accessory', 'network', 2100, 18,
    'RJ45 · cuivre · prêt à brancher', { packshot: '/photos/pack/net-cat6-20m.jpg', uses: ['office', 'gaming'] }),
  p('net-tp-cpl', 'TPL-PA4010-KIT', 'TP-Link CPL AV600 kit de 2', 'TP-Link', 'accessory', 'network', 7900, 4,
    'Internet par prise électrique', { packshot: '/photos/pack/net-tp-cpl.jpg', uses: ['office', 'gaming'] }),
  p('net-tp-mr600', 'TPL-MR600', 'TP-Link Archer MR600 routeur 4G+', 'TP-Link', 'accessory', 'network', 18400, 3,
    'Modem 4G LTE · Wi‑Fi AC1200', { packshot: '/photos/pack/net-tp-mr600.jpg', photoGroup: 'router-studio', uses: ['office', 'business'] }),
  p('pwr-apc-650', 'APC-BX650MI', 'APC Back-UPS 650 VA', 'APC', 'accessory', 'power', 18500, 4,
    'Onduleur · protection PC / routeur', { photoGroup: 'ups-studio', uses: ['office', 'business'] }),
  p('pwr-mustek-1200', 'MUSTEK-1200', 'Mustek PowerMust 1200 VA', 'Mustek', 'accessory', 'power', 26800, 3,
    'Onduleur bureau · AVR', { photoGroup: 'ups-studio', uses: ['office', 'business'] }),
  p('pwr-battery-9ah', 'UPS-12V-9AH', 'Batterie onduleur 12 V 9 Ah', 'Ritar', 'accessory', 'power', 3900, 8,
    'Batterie plomb étanche', { photoGroup: 'ups-studio', uses: ['office', 'business'] }),
  p('pwr-surge-6', 'SURGE-6-USB', 'Multiprise parafoudre 6 prises + USB', 'Ugreen', 'accessory', 'power', 4200, 10,
    'Protection surtension · 2 USB', { photoGroup: 'surge-studio', uses: ['office', 'gaming'] }),

  // ——— Accessoires laptop, écrans, multimédia, mobilité & bureau ———
  p('lapacc-ugreen-65w', 'UG-CD244-65W', 'Chargeur USB‑C Ugreen 65 W', 'Ugreen', 'accessory', 'laptop_accessories', 5900, 8,
    'GaN · USB‑C Power Delivery', {photoGroup: 'charger-studio',  uses: ['student', 'business'] }),
  p('lapacc-hp-65w', 'HP-65W-45MM', 'Chargeur laptop HP 65 W 4,5 mm', 'HP', 'accessory', 'laptop_accessories', 3900, 10,
    'Chargeur compatible HP', {photoGroup: 'charger-studio',  uses: ['student', 'business'] }),
  p('lapacc-ugreen-hub', 'UG-CM511', 'Hub USB‑C Ugreen 6-en-1', 'Ugreen', 'accessory', 'laptop_accessories', 7800, 6,
    'HDMI 4K · USB · SD · PD', { uses: ['student', 'business', 'creative'] }),
  p('lapacc-bag-15', 'BAG-15-6', 'Sacoche laptop 15,6 pouces', 'Havit', 'accessory', 'laptop_accessories', 2500, 15,
    'Poche accessoires · bandoulière', { uses: ['student', 'business'] }),
  p('lapacc-coolpad', 'COOLPAD-N8', 'Support refroidisseur laptop N8', 'Havit', 'accessory', 'laptop_accessories', 3900, 8,
    '2 ventilateurs · 15,6 pouces', { uses: ['gaming', 'student'] }),
  p('lapacc-sodimm-8', 'KVR32S22S8-8', 'Kingston 8 Go DDR4 SODIMM laptop', 'Kingston', 'accessory', 'laptop_accessories', 6800, 7,
    '3200 MHz · mémoire portable', {photoGroup: 'ram-studio',  uses: ['student', 'business'] }),
  // ——— Écrans ———
  p('mon-aoc-24b3', 'AOC-24B3HA2', 'AOC 24B3HA2 écran 24 pouces IPS', 'AOC', 'accessory', 'monitor', 24800, 5,
    'FHD · 100 Hz · bureautique', { packshot: '/photos/pack/mon-aoc-24b3.jpg', uses: ['office', 'student'] }),
  p('mon-samsung-g3-24', 'SAM-LS24G30', 'Samsung Odyssey G3 24"', 'Samsung', 'accessory', 'monitor', 26900, 6,
    '24" FHD · 165 Hz · 1 ms', { packshot: '/photos/pack/mon-samsung-g3-24.jpg', uses: ['gaming', 'office'] }),
  p('mon-lg-27-qhd', 'LG-27GS60QC', 'LG UltraGear 27" QHD', 'LG', 'accessory', 'monitor', 42900, 4,
    '27" QHD · 180 Hz · 1 ms', { packshot: '/photos/pack/mon-lg-27-qhd.jpg', uses: ['gaming', 'creative'] }),
  p('mon-dell-p2723de', 'DELL-P2723DE', 'Dell P2723DE 27" QHD', 'Dell', 'accessory', 'monitor', 48900, 3,
    '27" QHD · USB‑C · pivot', { packshot: '/photos/pack/mon-dell-p2723de.jpg', uses: ['business', 'office'] }),
  p('mon-samsung-s6-32', 'SAM-LS32C65', 'Samsung Smart Monitor S6 32"', 'Samsung', 'accessory', 'monitor', 57900, 2,
    '32" 4K · smart TV · USB‑C', { packshot: '/photos/pack/mon-samsung-s6-32.jpg', uses: ['office', 'creative'] }),
  p('mon-arm-north', 'ARM-F80', 'Bras articulé écran 17–32 pouces', 'North Bayou', 'accessory', 'furniture', 5200, 6,
    'Support VESA · bureau', { packshot: '/photos/pack/mon-arm-north.jpg', photoGroup: 'monitor-studio', uses: ['office', 'gaming', 'creative'] }),
  p('tab-samsung-a9', 'SAM-TABA9-64', 'Samsung Galaxy Tab A9 64 Go', 'Samsung', 'machine', 'tablet', 29800, 4,
    '8,7 pouces · Wi‑Fi', { photoGroup: 'tablet-studio', uses: ['student', 'office'] }),
  p('tab-huawei-t10', 'HUA-T10S-64', 'Huawei MatePad T10s 64 Go', 'Huawei', 'machine', 'tablet', 32500, 3,
    '10,1 pouces · Wi‑Fi', { photoGroup: 'tablet-studio', uses: ['student', 'office'] }),
  p('tab-wacom-small', 'WAC-CTL-472', 'Wacom One tablette graphique S', 'Wacom', 'accessory', 'multimedia', 8900, 4,
    'Stylet sans pile · création', { photoGroup: 'creative-studio', uses: ['creative', 'student'] }),
  p('media-epson-cow01', 'EPS-CO-W01', 'Epson CO-W01 vidéoprojecteur', 'Epson', 'accessory', 'multimedia', 68500, 2,
    'WXGA · HDMI · bureau / cours', { photoGroup: 'projector-studio', uses: ['office', 'student', 'business'] }),
  p('media-logi-c922', 'LOG-C922', 'Logitech C922 Pro Stream webcam', 'Logitech', 'accessory', 'multimedia', 14800, 4,
    'Full HD · micro stéréo', { uses: ['business', 'creative'] }),
  p('media-maono-aua04', 'MAONO-AUA04', 'Maono AU-A04 microphone USB', 'Maono', 'accessory', 'multimedia', 7800, 5,
    'Streaming · cours · podcast', { photoGroup: 'creative-studio', uses: ['creative', 'business'] }),
  p('media-logi-z313', 'LOG-Z313', 'Logitech Z313 enceintes 2.1', 'Logitech', 'accessory', 'multimedia', 9500, 5,
    '25 W · caisson de basses', {photoGroup: 'audio-studio',  uses: ['office', 'gaming'] }),
  p('media-meta-q3s', 'META-Q3S-128', 'Meta Quest 3S 128 Go VR', 'Meta', 'accessory', 'multimedia', 79000, 1,
    'Casque réalité virtuelle autonome', { photoGroup: 'creative-studio', uses: ['gaming', 'creative'] }),
  p('phone-pb20', 'UG-PB205-20K', 'Power bank Ugreen 20 000 mAh', 'Ugreen', 'accessory', 'phone', 6900, 10,
    'USB‑C PD · charge rapide', { uses: ['student', 'business'] }),
  p('phone-bt-neck', 'HAV-TW982', 'Écouteurs Bluetooth Havit TW982', 'Havit', 'accessory', 'phone', 4200, 12,
    'Bluetooth · boîtier charge', {photoGroup: 'audio-studio',  uses: ['student', 'office'] }),
  p('phone-car-30w', 'UG-CAR30W', 'Chargeur voiture Ugreen 30 W', 'Ugreen', 'accessory', 'phone', 2400, 10,
    'USB‑C PD + USB-A', { uses: ['student', 'business'] }),
  p('fur-havit-gc932', 'HAV-GC932', 'Chaise gamer Havit GC932', 'Havit', 'accessory', 'furniture', 34800, 2,
    'Accoudoirs réglables · dossier inclinable', {photoGroup: 'chair-studio',  uses: ['gaming', 'office'] }),
  p('fur-desk-120', 'DESK-120-60', 'Bureau PC 120 × 60 cm', 'Generic', 'accessory', 'furniture', 18500, 3,
    'Plateau bois · structure métal', { uses: ['office', 'gaming', 'student'] }),
  p('fur-laptop-stand', 'STAND-ALU-LAP', 'Support laptop aluminium réglable', 'Ugreen', 'accessory', 'furniture', 3600, 9,
    'Ventilé · pliable', { uses: ['student', 'business'] }),
  p('fur-safe-20', 'SAFE-20L', 'Coffre-fort électronique 20 L', 'Generic', 'accessory', 'furniture', 23800, 2,
    'Code PIN · clé de secours', { uses: ['business', 'retail'] })
]
